#!/bin/sh

TRIPLE=arm-linux-gnueabihf
SYSROOT=$SDKPATH/sysroot

export PKG_CONFIG_DIR=
export PKG_CONFIG_LIBDIR=${SYSROOT}/usr/local/lib/pkgconfig:${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/lib/${TRIPLE}/pkgconfig:${SYSROOT}/usr/share/pkgconfig

export PKG_CONFIG_SYSROOT_DIR=${SYSROOT}

exec pkg-config "$@"
